Support ubi8 docker images
elastic/apm-integration-testing pull request #931
Opened 2020-09-21 10:02 UTC by v1v

## What does this PR do?

Add `--ubi8` option to use ubi8 docker images. Verify `--oss` and `--ubi8` options are not enabled at the same time.

## Why is it important?

Support the ITs with the ubi8 minimal docker images when running them locally. 

__NOTE__: This particular option is not tested in the APM-ITs pipeline.

## Related issues

Closes https://github.com/elastic/apm-integration-testing/issues/900

## Test

```bash
$ BUILD_OPTS="--ubi8" ELASTIC_STACK_VERSION="8.0.0" .ci/scripts/go.sh
$ grep 'ubi8' docker-compose.yml 
      "image": "docker.elastic.co/apm/apm-server-ubi8:8.0.0-SNAPSHOT",
      "image": "docker.elastic.co/elasticsearch/elasticsearch-ubi8:8.0.0-SNAPSHOT",
$ docker ps
CONTAINER ID        IMAGE                                                               COMMAND                  CREATED             STATUS                            PORTS                                                                                                        NAMES
f4378529d269        docker.elastic.co/apm/apm-server-ubi8:8.0.0-SNAPSHOT                "/usr/local/bin/dock…"   9 seconds ago       Up 8 seconds (health: starting)   127.0.0.1:6060->6060/tcp, 127.0.0.1:8200->8200/tcp, 127.0.0.1:14250->14250/tcp, 127.0.0.1:14268->14268/tcp   localtesting_8.0.0_apm-server
a78a0dbc8094        docker.elastic.co/elasticsearch/elasticsearch-ubi8:8.0.0-SNAPSHOT   "/tini -- /usr/local…"   40 seconds ago      Up 39 seconds (healthy)           127.0.0.1:9200->9200/tcp, 9300/tcp                                                                           localtesting_8.0.0_elasticsearch

```

2020-09-21 10:31 UTC, axw requested changes
LGTM, thank you! Just one small comment about the binary name and:
 - I think Logstash is missing?
 - Could we please add UBI8 to the integration testing matrix?

2020-09-21 10:31 UTC, axw commented on scripts/modules/elastic_stack.py
> +                binary = "apm-server-ubi8"
```suggestion
            binary = "apm-server-oss" if self.oss else "apm-server"
```

The apm-server binary name does not change for the ubi8 images; only for OSS.

2020-09-21 10:40 UTC, apmmachine commented
## :broken_heart: Tests Failed


<!-- BUILD BADGES-->
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests%2FPR-931/detail/PR-931/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests%2FPR-931/detail/PR-931/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests%2FPR-931/detail/PR-931/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://apm-ci.elastic.co/blue/organizations/jenkins/apm-integration-tests%2FPR-931/detail/PR-931/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://apm-integration-testing_931.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #931 opened]`

* Start Time: 2020-09-21T10:02:53.875+0000

* Duration: 38 min 46 sec




#### Test stats :test_tube:

| Test         | Results                         |
| ------------ | :-----------------------------: |
| Failed       | 2  |
| Passed       | 410  |
| Skipped      | 14 |
| Total        | 426   |


</p>
</details>

<!-- TEST RESULTS IF ANY-->

  ### Test errors
  <details><summary>Expand to view the tests failures</summary>
  <p>
    
* **Name**: `Integration Tests / All / test_express_error – tests.agent.test_nodejs`
  * Age: 1
  * Duration: 30.136
  * Error Details: AssertionError: Expected 1, queried -1
    
* **Name**: `Integration Tests / All / test_conc_req_express – tests.agent.test_nodejs`
  * Age: 1
  * Duration: 31.663
  * Error Details: AssertionError: queried for [('processor.event', 'transaction'), ('service.name', ['expressapp'])], expected 1000, got 1001
    
  </p>
  </details>


<!-- STEPS ERRORS IF ANY-->


### Steps errors

  <details><summary>Expand to view the steps failures</summary>
  <p>
  
  * **Name**: `Error signal`
    * Description: Downstream job for 'All' failed
    
    * Duration: 0 min 0 sec
    
    * Start Time: 2020-09-21T10:40:35.538+0000
    
    * [log](https://apm-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/apm-integration-tests/pipelines/PR-931/runs/1/steps/183/log)
    
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-09-21T10:07:27.003Z] Collecting zipp>=0.5
[2020-09-21T10:07:27.003Z]   Downloading zipp-1.2.0-py2.py3-none-any.whl (4.8 kB)
[2020-09-21T10:07:27.003Z] Collecting configparser>=3.5; python_version < "3"
[2020-09-21T10:07:27.003Z]   Downloading configparser-4.0.2-py2.py3-none-any.whl (22 kB)
[2020-09-21T10:07:27.003Z] Collecting typing; python_version < "3.5"
[2020-09-21T10:07:27.003Z]   Downloading typing-3.7.4.3-py2-none-any.whl (26 kB)
[2020-09-21T10:07:27.003Z] Collecting singledispatch; python_version < "3.4"
[2020-09-21T10:07:27.003Z]   Downloading singledispatch-3.4.0.3-py2.py3-none-any.whl (12 kB)
[2020-09-21T10:07:27.268Z] Collecting scandir; python_version < "3.5"
[2020-09-21T10:07:27.268Z]   Downloading scandir-1.10.0.tar.gz (33 kB)
[2020-09-21T10:07:27.531Z] Building wheels for collected packages: pyyaml, filelock, scandir
[2020-09-21T10:07:27.531Z]   Building wheel for pyyaml (setup.py): started
[2020-09-21T10:07:28.109Z]   Building wheel for pyyaml (setup.py): finished with status 'done'
[2020-09-21T10:07:28.109Z]   Created wheel for pyyaml: filename=PyYAML-5.3.1-cp27-cp27mu-linux_x86_64.whl size=45643 sha256=875024f68adfdd5c2762d6dc064dd428a0641abf714e00c3f9a3406325e5012c
[2020-09-21T10:07:28.109Z]   Stored in directory: /var/lib/jenkins/workspace/apm-integration-tests_PR-931/.cache/pip/wheels/d1/d5/a0/3c27cdc8b0209c5fc1385afeee936cf8a71e13d885388b4be2
[2020-09-21T10:07:28.109Z]   Building wheel for filelock (setup.py): started
[2020-09-21T10:07:28.109Z]   Building wheel for filelock (setup.py): finished with status 'done'
[2020-09-21T10:07:28.109Z]   Created wheel for filelock: filename=filelock-3.0.12-py2-none-any.whl size=7578 sha256=c0ed5c1de0e6a947d4f277a16af954b4ed0bb7b0e55371f4c6395277a91bd578
[2020-09-21T10:07:28.109Z]   Stored in directory: /var/lib/jenkins/workspace/apm-integration-tests_PR-931/.cache/pip/wheels/b9/91/23/b559c1f4fd55056712b3a71cd9cab1dc0089e2232d502ed72e
[2020-09-21T10:07:28.109Z]   Building wheel for scandir (setup.py): started
[2020-09-21T10:07:28.686Z]   Building wheel for scandir (setup.py): finished with status 'done'
[2020-09-21T10:07:28.686Z]   Created wheel for scandir: filename=scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl size=33232 sha256=b7c33087b5ae3f4232b8064f5691f518d01c46278d9c150f2c3fcc0f34c6a062
[2020-09-21T10:07:28.686Z]   Stored in directory: /var/lib/jenkins/workspace/apm-integration-tests_PR-931/.cache/pip/wheels/58/2c/26/52406f7d1f19bcc47a6fbd1037a5f293492f5cf1d58c539edb
[2020-09-21T10:07:28.686Z] Successfully built pyyaml filelock scandir
[2020-09-21T10:07:28.949Z] Installing collected packages: futures, pyyaml, aspy.yaml, contextlib2, zipp, configparser, scandir, six, pathlib2, importlib-metadata, typing, singledispatch, importlib-resources, appdirs, distlib, filelock, virtualenv, toml, cfgv, nodeenv, identify, pre-commit
[2020-09-21T10:07:29.527Z] Successfully installed appdirs-1.4.4 aspy.yaml-1.3.0 cfgv-2.0.1 configparser-4.0.2 contextlib2-0.6.0.post1 distlib-0.3.1 filelock-3.0.12 futures-3.3.0 identify-1.5.3 importlib-metadata-1.7.0 importlib-resources-3.0.0 nodeenv-1.5.0 pathlib2-2.3.5 pre-commit-1.21.0 pyyaml-5.3.1 scandir-1.10.0 singledispatch-3.4.0.3 six-1.15.0 toml-0.10.1 typing-3.7.4.3 virtualenv-20.0.31 zipp-1.2.0
[2020-09-21T10:07:29.790Z] Downloading https://files.pythonhosted.org/packages/a4/e3/1f067de470e3a86875ed915438dc3bd781fb0346254f541190a09472b677/virtualenv-16.7.10.tar.gz
[2020-09-21T10:07:29.790Z] Done.
[2020-09-21T10:07:29.790Z] *******************************************************************************
[2020-09-21T10:07:29.790Z] Installing pre-commit to /var/lib/jenkins/workspace/apm-integration-tests_PR-931/bin/pre-commit
[2020-09-21T10:07:29.790Z] *******************************************************************************
[2020-09-21T10:07:29.790Z] It looks like /var/lib/jenkins/workspace/apm-integration-tests_PR-931/bin is not on your path
[2020-09-21T10:07:29.790Z] You may want to add it.
[2020-09-21T10:07:29.790Z] Often this does the trick: source ~/.profile
[2020-09-21T10:07:30.206Z] + export PATH=/var/lib/jenkins/workspace/apm-integration-tests_PR-931/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[2020-09-21T10:07:30.206Z] + pre-commit install --install-hooks
[2020-09-21T10:07:30.469Z] pre-commit installed at .git/hooks/pre-commit
[2020-09-21T10:07:30.469Z] [INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[2020-09-21T10:07:31.044Z] [INFO] Initializing environment for https://github.com/detailyang/pre-commit-shell.git.
[2020-09-21T10:07:31.618Z] [INFO] Initializing environment for https://github.com/adrienverge/yamllint.git.
[2020-09-21T10:07:32.193Z] [INFO] Initializing environment for git@github.com:elastic/apm-pipeline-library.
[2020-09-21T10:07:33.148Z] [INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[2020-09-21T10:07:33.148Z] [INFO] Once installed this environment will be reused.
[2020-09-21T10:07:33.148Z] [INFO] This may take a few minutes...
[2020-09-21T10:07:41.317Z] [INFO] Installing environment for https://github.com/adrienverge/yamllint.git.
[2020-09-21T10:07:41.317Z] [INFO] Once installed this environment will be reused.
[2020-09-21T10:07:41.317Z] [INFO] This may take a few minutes...
[2020-09-21T10:07:43.584Z] + export PATH=/var/lib/jenkins/workspace/apm-integration-tests_PR-931/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
[2020-09-21T10:07:43.584Z] + set +e
[2020-09 [...]

2020-09-21 10:54 UTC, kuisathaverat approved these changes

2020-09-21 15:04 UTC, kuisathaverat approved these changes

2020-09-22 00:54 UTC, axw approved these changes
Perfect, thank you!

2020-09-22 08:19 UTC, merged